### ISSUE TITLE
HDD write issue (and maybe in FAT16 driver)

### ISSUE THREAD

**Issue by AzuxDario** [skni-kod/MicrOS#89]
When more than one sector is written to the HDD, disk is blocked.
Current workaround is to add delay between writes.

This occurs in `int8_t __harddisk_ata_poll(uint16_t control_port)` funciton when `result.value == 0x50`

**Comment by AzuxDario** [comment]
Now this function returns 0 when affected to avoid system block.

**Comment by AzuxDario** [comment]
I made some changes, longer delay, usage of io port instead of control port. Albo when SERV bit sets instead of DRQ I also made it as ok situation. Now making files doesn't block system. But files and folders made in other folders doesn't appear in MicrOS. However when I look into hdd.img file I see their names. This needs further investigation.

**Comment by AzuxDario** [comment]
![Przechwytywanie](https://user-images.githubusercontent.com/26147393/115733700-69742b00-a389-11eb-89c8-7c673420e397.PNG)
For example this file AAAABBBBCCC that I made in folder.

**Comment by AzuxDario** [comment]
Detection of disks has been fixed

**Comment by MinusPL** [comment]
Closed since being consolidated in #134
